import os,sys
from src.constants import *

ROOT_DIR=ROOT_DIR
API_FETHED_DATA=os.path.join(ROOT_DIR,DATA_DIR_FOLDER)
CURRENT_DATA_PATH=os.path.join(ROOT_DIR,CURRENT_DATA_FOLDER,CURRENT_DATA_FILE)
RAW_TRAIN_DATASET_PATH=os.path.join(ROOT_DIR,DATA_DIR_FOLDER,DATA_DIR_TRAIN)
RAW_TEST_DATASET_PATH=os.path.join(ROOT_DIR,DATA_DIR_FOLDER,DATA_DIR_TEST)
RAW_SS_DATASET_PATH=os.path.join(ROOT_DIR,DATA_DIR_FOLDER,DATA_DIR_SS)



RAW_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_FOLDER,DATA_INJECTION_FOLDER,
                           DATA_INJECTION_RAW_DATA_FOLDER,DATA_INJECTION_INJECTED_DATA_FILE)

TRAIN_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_FOLDER,DATA_INJECTION_FOLDER,
                            DATA_INJECTION_INJECTED_DATA_FOLDER,INJECTED_TRAIN_DATA)

TEST_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_FOLDER,DATA_INJECTION_FOLDER,
                            DATA_INJECTION_INJECTED_DATA_FOLDER,INJECTED_TEST_DATA)